language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  # - wget https://phar.phpunit.de/phpunit.phar
  # - chmod +x phpunit.phar
  # - sudo mv phpunit.phar /usr/local/bin/phpunit
  # - phpunit --version
  - git clone https://github.com/octobercms/october.git
  - mkdir -p ./october/plugins/sublimearts/sublimechimp
  - mv !(october) october/plugins/sublimearts/sublimechimp
  - cd october
  - composer install
  - cd plugins/sublimearts/sublimechimp
  - composer install
  - composer dump-autoload
  # - mkdir -p ../../rainlab
  # - cd ../../rainlab
  # - git clone https://github.com/rainlab/user-plugin
  # - mv user-plugin user
  # - cd user
  # - composer install
  # - cd ../../sublimearts/sublimechimp

script: phpunit