# ===================================
#  Relation Behavior Config
# ===================================

recipients:
    label: Recipients
    
    view:
        list: $/sublimearts/sublimechimp/models/recipient/columns.yaml
        toolbarButtons: add|remove
    manage:
        list: $/sublimearts/sublimechimp/models/recipient/columns.yaml
    pivot:
        form: $/sublimearts/sublimechimp/models/recipient/fields.yaml